name: Update Gradle Wrapper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  - uses: actions/checkout@v6
    with:
      persist-credentials: false

    steps:
      - uses: actions/checkout@v6

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v2